### ISSUE TITLE
ERROR ~ Error executing process > 'pipeline:makeReport'

### ISSUE THREAD

**Issue by laurenlansdowne** [epi2me-labs/wf-flu#12]
### Operating System

Windows 10

### Workflow Version

23.04.2

### Workflow Execution

EPI2ME Desktop (Local)

### EPI2ME Version

v5.2.1

### Workflow Execution - CLI Execution Profile

None

### What happened?

Stopped with error

### Relevant log output

```shell
Core Nextflow options
  runName        : flamboyant_connor
  containerEngine: docker
  launchDir      : /mnt/c/Users/lansdole/epi2melabs/instances/wf-flu_01JA5H4KHSX80W2WP3VQSSNTWM
  workDir        : /mnt/c/Users/lansdole/epi2melabs/instances/wf-flu_01JA5H4KHSX80W2WP3VQSSNTWM/work
  projectDir     : /mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu
  userName       : epi2mewsl
  profile        : standard
  configFiles    : /mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu/nextflow.config
Input Options
  fastq          : /mnt/c/Users/lansdole/Desktop/Sequencing Data/LL_flu_and_plant_test_10_10_24/fastq_pass/barcode04/FBA62538_pass_barcode04_b32a4180_8dbdcf08_10.fastq.gz
Output Options
  out_dir        : /mnt/c/Users/lansdole/epi2melabs/instances/wf-flu_01JA5H4KHSX80W2WP3VQSSNTWM/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-flu for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-flu v1.2.3.
--------------------------------------------------------------------------------
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
NOT Downsampling!!!
[11/7f191f] Submitted process > fastcat (1)
[7a/486e2a] Submitted process > pipeline:getParams
[23/623ef6] Submitted process > pipeline:getVersions
[fb/7411e2] Submitted process > pipeline:alignReads (1)
[88/487b14] Submitted process > pipeline:coverageCalc (1)
[86/1c2422] Submitted process > pipeline:medakaVariants (1)
[1d/ec2ea3] Submitted process > pipeline:makeConsensus (1)
[2a/c5df56] Submitted process > pipeline:typeFlu (1)
[e2/0d5b68] Submitted process > pipeline:processType (1)
[c7/27bf21] Submitted process > pipeline:prepNextclade (1)
[c1/e1e843] Submitted process > pipeline:collectFilesInDir (1)
[c2/9b9a6b] Submitted process > pipeline:nextclade (1)
[a5/a6e745] Submitted process > pipeline:nextclade (2)
[74/0e28c5] Submitted process > pipeline:makeReport
ERROR ~ Error executing process > 'pipeline:makeReport'
Caused by:
  Process `pipeline:makeReport` terminated with an error exit status (1)
Command executed:
  echo '[
      {
          "barcode": null,
          "type": "test_sample",
          "run_ids": [
              "8dbdcf08518f045d5dc8f9f5e393a714691a1d5a"
          ],
          "basecall_models": [
              "dna_r10.4.1_e8.2_400bps_hac@v4.3.0"
          ],
          "alias": "FBA62538_pass_barcode04_b32a4180_8dbdcf08_10",
          "group_key": {
              "groupTarget": "FBA62538_pass_barcode04_b32a4180_8dbdcf08_10",
              "groupSize": 1
          },
          "n_fastq": 1,
          "group_index": "FBA62538_pass_barcode04_b32a4180_8dbdcf08_10_0",
          "n_seqs": 9617
      }
  ]' > metadata.json
      workflow-glue report "wf-flu-report.html"        --data data         --stats stats_         --versions versions         --params params.json         --nextclade_files nextclade/*         --nextclade_datasets "nextclade.csv"         --metadata metadata.json         --workflow_version v1.2.3
Command exit status:
  1
Command output:
  (empty)
Command error:
  [12:50:16 - workflow_glue] Bootstrapping CLI.
  [12:50:25 - matplotlib.font_manager] generated new fontManager
  [12:50:26 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu/bin/workflow-glue", line 7, in <module>
      cli()
    File "/mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu/bin/workflow_glue/report.py", line 128, in main
      get_row_format(row)
    File "/mnt/c/Users/lansdole/epi2melabs/workflows/epi2me-labs/wf-flu/bin/workflow_glue/report.py", line 85, in get_row_format
      cell.add(td(span(row)))
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/dominate/tags.py", line 63, in __init__
      super(html_tag, self).__init__(*args, **kwargs)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/dominate/dom_tag.py", line 129, in __init__
      self.add(*args)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/dominate/dom_tag.py", line 237, in add
      raise ValueError('%r not a tag or string.' % obj)
  ValueError: None not a tag or string.
Work dir:
  /mnt/c/Users/lansdole/epi2melabs/instances/wf-flu_01JA5H4KHSX80W2WP3VQSSNTWM/work/74/0e28c5cfc4887d38285dae09e1c970
Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
 -- Check '/mnt/c/Users/lansdole/epi2melabs/instances/wf-flu_01JA5H4KHSX80W2WP3VQSSNTWM/nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

other (please describe below)

**Comment by BioWilko** [comment]
@SamStudio8 @cjw85 :)

**Comment by cjalder** [comment]
Hi @laurenlansdowne - this issue has been identified internally and we should have a fix in the next release cycle.
