### ISSUE TITLE
[Bug]: pipeline:prepNextclade is not able to process samples with unknown Type

### ISSUE THREAD

**Issue by RasmusKoRiis** [epi2me-labs/wf-flu#4]
### What happened?

The process pipeline:prepNextclade fails and terminates the whole process when trying to process a sample with a unknown type (not classfied as either A or B). See error message:

  **WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  [22:25:33 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow-glue", line 7, in <module>
      cli()
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/__init__.py", line 62, in cli
      args.func(args)
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/nextclade_helper.py", line 84, in main
      datasets = find_nextclade(typing, args.nextclade_datasets)
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/nextclade_helper.py", line 40, in find_nextclade
      raise ValueError(f'{flu_type} is not Type_A or Type_B')
  ValueError: undetermined is not Type_A or Type_B**

_It would also be nice to include **type** and **subtype** in the wf-flu-results.csv file. Thesse columns are removed but were included in v0.0.6._

### Operating System

macOS

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v0.0.9 and v0.0.10

### Relevant log output

```shell
**WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  [22:25:33 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow-glue", line 7, in <module>
      cli()
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/__init__.py", line 62, in cli
      args.func(args)
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/nextclade_helper.py", line 84, in main
      datasets = find_nextclade(typing, args.nextclade_datasets)
    File "/Users/X/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/nextclade_helper.py", line 40, in find_nextclade
      raise ValueError(f'{flu_type} is not Type_A or Type_B')
  ValueError: undetermined is not Type_A or Type_B**
```

**Comment by mattdmem** [comment]
Hi @RasmusKoRiis,

Apologies for the tardy reply. We'll take a look at this and get a fix out.

Matt

**Comment by mattdmem** [comment]
@RasmusKoRiis - a fix should have been released for this. Please open another issue if you are still having problems.

Thanks

Matt
